import "../styles/globals.css";
// import localFont from "next/font/local";
import MainNavigation from "../components/layout/MainNavigation";
import SectionContainer from "components/SectionContainer";
import Header from "components/Header";
import { ThemeProviders } from "./providers/ThemeProviders";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className="bg-white pl-[calc(100vw-100%)] text-black antialiased dark:bg-gray-950 dark:text-white">
        <ThemeProviders>
          <SectionContainer>
            <Header />
            {/* <MainNavigation></MainNavigation> */}
            <main className="mb-auto">{children}</main>
            <div id="notifications"></div>
          </SectionContainer>
        </ThemeProviders>
      </body>
    </html>
  );
}
