import '../styles/globals.css'
// import localFont from "next/font/local";
import MainNavigation from "../components/layout/MainNavigation";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='m-6 bg-amber-100'>
        <MainNavigation></MainNavigation>
        {children}
        <div id="notifications"></div>
      </body>
    </html>
  );
}
