import { allPosts } from "contentlayer/generated";
import { compareDesc } from "date-fns";
import Main from "./Main";

export const metadata = {
  title: "Max's blog",
  description: "Generated by create next app",
};

export default function Homepage() {
  const posts = allPosts.sort((a, b) =>
    compareDesc(new Date(a.date), new Date(b.date))
  );

  return (
    <div>
      <Main posts={posts} />
    </div>
  );
}
