import { Fragment } from "react";
import FearturedPost from "./components/home-page/FeaturedPosts";
import Hero from "./components/home-page/Hero";
import { getFeaturedPosts } from "./lib/posts-util";

// const DUMMY_POSTS = [
//   {
//     slug: "getting-started-nextjs",
//     title: "getting started with nextjs",
//     image: "getting-started-nextjs.png",
//     excerpt: "NextJs is the Reat Framework",
//     date: "2024-10-29",
//   },
//   {
//     slug: "getting-started-with-nextjs2",
//     title: "getting started with nextjs2",
//     image: "getting-started-nextjs.png",
//     excerpt: "NextJs is the Reat Framework",
//     date: "2024-10-29",
//   },
//   {
//     slug: "getting-started-with-nextjs3",
//     title: "getting started with nextjs3",
//     image: "getting-started-nextjs.png",
//     excerpt: "NextJs is the Reat Framework",
//     date: "2024-10-29",
//   },
// ];

export const metadata = {
  title: "Max's blog",
  description: "Generated by create next app",
};

export default function Homepage(props) {
  const featuredPosts = getFeaturedPosts();
  console.log(featuredPosts);

  return (
    <Fragment>
      <Hero></Hero>
      <FearturedPost posts={featuredPosts}></FearturedPost>
    </Fragment>
  );
}
